## The function makeCacheMatrix can be run by
## 
## y <- makeCacheMatrix(M)
## 
## where M is a given invertible matrix 
## ( previously generated by - for example:
## 
## M <- matrix(c(1,0,0,0,4,0,0,0,9),3,3) 
##
##  ).
## 
## The function cacheSolve can be run by
## 
## cacheSolve(y)
## 
## where y is the previously generated list of functions.

## The function makeCacheMatrix generates a list of functions.
## 1) The first component of the list is the function "get". It returns
## the value x, which is the argument of the function makeCacheMatrix.
## 2) The second component of the list is the function "setinverse",
## which has the argument "inverse1" and assigns the value of this argument
## to the variable "invmat" from the enclosing environment of the function
## x$setinverse()
## 3) The last component of the list is the function "getinverse", which returns
## the value of the variable "invmat" from the enclosing environment of 
## the function x$getinverse(), which is also the environment of the function
## x$setinverse(). 
## It finally creates the list and returns its components, 
## i.e. the functions get, setinverse and getinverse 
## including their common environment, which is something like
## "<environment: 0x00000000134a0128>". 
## This environment plays the role of the "cache". 

makeCacheMatrix <- function(x = matrix()) {
      invmat <- NULL

      get <- function() x
      setinverse <- function(inverse1) invmat <<- inverse1
      getinverse <- function() invmat 
      list(get = get,
            setinverse = setinverse,
            getinverse = getinverse)

}


## The function cacheSolve makes the following steps:
## 1. It runs the function x$getinverse() 
## The result is the value of the variable "invmat" from the environment
## of the function x$getinverse(),
## which is NULL (if the inverse has NOT been previously computed, i.e.
## the cache is empty) or the 
## "cached" inverse matrix (if the inverse has been previously computed)
## 2. It checks whether the variable invmat is NULL.
## If not, then it returns the cached data and stops the function.
## If yes, it then runs the function x$get(), assigns the result to the variable 
## data, and computes the inverse of the matrix with solve().
## 3. It "caches" the result by running the function x$setinverse, which assigns
## the value of its argument to the variable "invmat" from the environment of the
## function x$setinverse. 
## 4. Finally, it returns the value of "invmat".

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  invmat <- x$getinverse()
  
  if(!is.null(invmat)) {
    message("getting cached data")
    return(invmat)
  }
  
  data <- x$get()
  invmat <- solve(data, ...)
  x$setinverse(invmat)
  invmat
}
