## The function makeCacheMatrix can be run by y <- makeCacheMatrix(M),
## where M is a given invertible matrix (the input data) 
## (e.g previously generated by M <- matrix(c(1,0,0,0,4,0,0,0,10),3,3) ).
## The function cacheSolve can be run by cacheSolve(y),
## where y is the previously generated list of functions. If the "cached" inverse 
## is available AND the input data has not been changed, the function returns the
## "cached" inverse. If the input data has been changed, the new input data is 
## stored in "cache" and the "cached" inverse is removed. If the "cached"
## inverse is not available, the inverse of the input data is computed.
## 
## Description of the function makeCacheMatrix():
## The function makeCacheMatrix generates a list of functions.
## 1) The first component of the list is the function "set", which can RESET the 
## input data and the "cached" data
## 2) The second component of the list is the function "get". It returns
## the value of the free variable x, which is stored in the parent environment,  
## being the argument of the function makeCacheMatrix.
## 3) The third component of the list is the function "setinverse",
## which has the argument "inverse1" and assigns the value of this argument
## to the variable "invmat" from the enclosing environment of the function
## x$setinverse()
## 4) The last component of the list is the function "getinverse", which returns
## the value of the variable "invmat" from the enclosing environment of 
## the function x$getinverse(), which is also the environment of the function
## x$setinverse(). 
## It finally creates the list and returns its components, 
## i.e. the functions set, get, setinverse and getinverse 
## including their common environment, which is something like
## "<environment: 0x00000000134a0128>". 
## This environment plays the role of the "cache". 

makeCacheMatrix <- function(x = matrix()) {
      invmat <- NULL
      
      set <- function(y) {
        x <<- y
        invmat <<- NULL
      }
      get <- function() x
      setinverse <- function(inverse1) invmat <<- inverse1
      getinverse <- function() invmat 
      list(set = set, get = get,
            setinverse = setinverse,
            getinverse = getinverse)

}

## Description of the function cacheSolve():
## The function cacheSolve takes the following steps:
## 1. It runs the function x$getinverse() 
## The result is the value of the variable "invmat" from the environment
## of the function x$getinverse(),
## which is NULL (if the inverse has NOT been previously computed, i.e.
## the cache is empty) or the 
## "cached" inverse matrix (if the inverse has been previously computed).
## 2. It checks whether the variable invmat is NULL.
## If not, then it checks if the input data has been changed. If the input data 
## has NOT been changed, it returns the cached data and stops cacheSolve().
## If the input data has been changed, it resets the data.  
## It then runs the function x$get(), assigns the result to the variable 
## data, and computes the inverse of the matrix with solve().
## 3. It "caches" the result by running the function x$setinverse, which assigns
## the value of its argument to the variable "invmat" from the environment of the
## function x$setinverse. 
## 4. Finally, it returns the value of "invmat".

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        invmat <- x$getinverse()
  
        if(!is.null(invmat) ) {
                data <- x$get()
                if (identical(M,data)) {
                      message("getting cached data")
                      return(invmat)
                } else {
                      message("setting the new input data and resetting the cached data")
                      x$set(M)
                        }
        }
  
  data <- x$get()
  invmat <- solve(data, ...)
  x$setinverse(invmat)
  invmat
}
